import {
  DrawioStencil,
  findStencilByName,
  loadDrawioStencils,
  toTypeName
} from '../drawioStencilLoader';
import { NodeDefinitionRegistry } from '@diagram-craft/model/elementDefinitionRegistry';
import { Box } from '@diagram-craft/geometry/box';
import { ShapeParser, Style } from '../drawioReader';
import { Diagram } from '@diagram-craft/model/diagram';
import { Layer } from '@diagram-craft/model/diagramLayer';
import { DiagramNode, NodeTexts } from '@diagram-craft/model/diagramNode';
import { Extent } from '@diagram-craft/geometry/extent';
import { FlexShapeNodeDefinition } from '@diagram-craft/canvas/node-types/FlexShapeNodeDefinition';
import { RectNodeDefinition } from '@diagram-craft/canvas/node-types/Rect.nodeType';
import { DrawioShapeNodeDefinition } from '../DrawioShape.nodeType';

const stencilDimensions = new Map<string, Extent>();

const registerStencil = (
  registry: NodeDefinitionRegistry,
  name: string,
  stencils: Array<DrawioStencil>
) => {
  const stencil = findStencilByName(stencils, name);

  const node = new DrawioShapeNodeDefinition(`mxgraph.aws4.${toTypeName(name)}`, name, stencil);
  stencilDimensions.set(node.type, stencil.dimensions!);

  registry.register(node);
};

export const parseAWS4Shapes = async (
  id: string,
  bounds: Box,
  props: NodeProps,
  metadata: ElementMetadata,
  texts: NodeTexts,
  style: Style,
  diagram: Diagram,
  layer: Layer
): Promise<DiagramNode> => {
  const fg = props.stroke?.color;

  props.custom ??= {};

  if (style.shape === 'mxgraph.aws4.resourceIcon') {
    const MARGIN = 0.1;

    const dim = stencilDimensions.get(style!.resIcon!)!;

    let fgBounds: Box;
    if (dim.h > dim.w) {
      const w = (1 - 2 * MARGIN) * (dim.w / dim.h);
      fgBounds = { w: w, h: 1 - 2 * MARGIN, x: (1 - w) / 2, y: MARGIN, r: 0 };
    } else {
      const h = (1 - 2 * MARGIN) * (dim.h / dim.w);
      fgBounds = { w: 1 - 2 * MARGIN, h: h, x: MARGIN, y: (1 - h) / 2, r: 0 };
    }

    props.custom.flex ??= {};
    props.custom.flex.components = [
      {
        id: 'icon',
        nodeType: style!.resIcon!,
        bounds: fgBounds,
        props: {
          fill: {
            color: fg,
            type: 'solid'
          }
        }
      }
    ];

    return new DiagramNode(
      id,
      'mxgraph.aws4.resourceIcon',
      bounds,
      diagram,
      layer,
      props,
      metadata,
      texts
    );
  } else if (style.shape === 'mxgraph.aws4.group' || style.shape === 'mxgraph.aws4.groupCenter') {
    if (style.grStroke === '0') {
      props.stroke = { enabled: false };
    }

    props.custom.flex ??= {};
    props.custom.flex.components = [
      {
        id: 'icon',
        nodeType: style!.grIcon!,
        props: {
          fill: {
            color: fg,
            type: 'solid'
          }
        }
      }
    ];

    return new DiagramNode(id, style.shape, bounds, diagram, layer, props, metadata, texts);
  }

  if (style.shape?.includes('illustration')) {
    props.custom.drawio ??= {};
    props.custom.drawio!.textPosition = 'bottom';
  }

  return new DiagramNode(id, style.shape!, bounds, diagram, layer, props, metadata);
};

export const registerAWS4Shapes = async (
  r: NodeDefinitionRegistry,
  shapeParsers: Record<string, ShapeParser>
) => {
  const stencils = await loadDrawioStencils('/stencils/aws4.xml', 'AWS4', '#005073', '#005073');

  shapeParsers['mxgraph.aws4.resourceIcon'] = parseAWS4Shapes;
  shapeParsers['mxgraph.aws4.group'] = parseAWS4Shapes;

  shapeParsers['mxgraph.aws4.illustration_desktop'] = parseAWS4Shapes;
  shapeParsers['mxgraph.aws4.illustration_devices'] = parseAWS4Shapes;
  shapeParsers['mxgraph.aws4.illustration_notification'] = parseAWS4Shapes;
  shapeParsers['mxgraph.aws4.illustration_office_building'] = parseAWS4Shapes;
  shapeParsers['mxgraph.aws4.illustration_users'] = parseAWS4Shapes;

  // Register some node definitions that are needed for AWS4 shapes
  r.register(
    new FlexShapeNodeDefinition('mxgraph.aws4.resourceIcon', 'AWS Resource Icon', {
      isGroup: false,
      boundary: new RectNodeDefinition(),
      components: [
        {
          id: 'icon',
          props: {
            stroke: {
              enabled: false
            }
          }
        }
      ]
    })
  );
  r.register(
    new FlexShapeNodeDefinition('mxgraph.aws4.group', 'AWS Group', {
      isGroup: true,
      boundary: new RectNodeDefinition(),
      text: {
        id: '1'
      },
      components: [
        {
          id: 'icon',
          bounds: {
            w: 0,
            h: 0,
            x: 0,
            y: 0,
            r: 0
          },
          offset: {
            x: 0,
            y: 0,
            w: 25,
            h: 25
          }
        }
      ]
    })
  );
  r.register(
    new FlexShapeNodeDefinition('mxgraph.aws4.groupCenter', 'AWS Group Center', {
      isGroup: true,
      boundary: new RectNodeDefinition(),
      text: {
        id: '1'
      },
      components: [
        {
          id: 'icon',
          bounds: {
            w: 0,
            h: 0,
            x: 0.5,
            y: 0,
            r: 0
          },
          offset: {
            x: -12.5,
            y: 0,
            w: 25,
            h: 25
          },
          props: {
            stroke: {
              enabled: false
            }
          }
        }
      ]
    })
  );

  const stencilList = [
    'A1 Instance',
    'Access Analyzer',
    'Action',
    'Activate',
    'Actuator',
    'Ad Connector',
    'Addon',
    'Agent',
    'Agent2',
    'Alarm',
    'Alert',
    'Alexa Enabled Device',
    'Alexa For Business',
    'Alexa Skill',
    'All Products',
    'Ami',
    'Amplify Aws Amplify Studio',
    'Amplify',
    'Analytics',
    'Apache Mxnet On Aws',
    'Api Gateway',
    'App Config',
    'App Mesh',
    'App Runner',
    'App Wizard',
    'Appfabric',
    'Appflow',
    'Application Auto Scaling',
    'Application Composer',
    'Application Cost Profiler',
    'Application Discovery Service Aws Agentless Collector',
    'Application Discovery Service Aws Discovery Agent',
    'Application Discovery Service Migration Evaluator Collector',
    'Application Discovery Service',
    'Application Integration',
    'Application Load Balancer',
    'Application',
    'Appstream 20',
    'Appsync',
    'Ar Vr',
    'Archive',
    'Artifact',
    'Athena Data Source Connectors',
    'Athena',
    'Attribute',
    'Attributes',
    'Audit Manager',
    'Augmented Ai',
    'Aurora Instance Alt',
    'Aurora Instance',
    'Aurora',
    'Authenticated User',
    'Auto Scaling2',
    'Auto Scaling3',
    'Automation',
    'Autoscaling',
    'Aws Backup For Aws Cloudformation',
    'Aws Backup Legal Hold',
    'Aws Backup Support For Amazon Fsx For Netapp Ontap',
    'Aws Backup Vault Lock',
    'Aws Glue Data Quality',
    'Aws Glue For Ray',
    'B2b Data Interchange',
    'Backint Agent',
    'Backup Audit Manager',
    'Backup Aws Backup Support For Amazon S3',
    'Backup Aws Backup Support For Vmware Workloads',
    'Backup Compliance Reporting',
    'Backup Compute',
    'Backup Database',
    'Backup Gateway',
    'Backup Plan',
    'Backup Recovery Point Objective',
    'Backup Recovery Time Objective',
    'Backup Restore',
    'Backup Storage',
    'Backup Vault',
    'Backup Virtual Machine Monitor',
    'Backup Virtual Machine',
    'Backup',
    'Bank',
    'Batch',
    'Bedrock',
    'Blockchain Resource',
    'Blockchain',
    'Bottlerocket',
    'Braket Chandelier',
    'Braket Chip',
    'Braket Embedded Simulator',
    'Braket Managed Simulator',
    'Braket Noise Simulator',
    'Braket Qpu',
    'Braket Simulator 1',
    'Braket Simulator 2',
    'Braket Simulator 3',
    'Braket Simulator 4',
    'Braket Simulator',
    'Braket State Vector',
    'Braket Tensor Network',
    'Braket',
    'Bucket With Objects',
    'Bucket',
    'Budgets 2',
    'Business Application',
    'Bycicle',
    'C4 Instance',
    'C5 Instance',
    'C5a',
    'C5ad',
    'C5d',
    'C5n Instance',
    'C6g Instance',
    'C6gd',
    'Cache Node',
    'Cached Volume',
    'Camera',
    'Camera2',
    'Car',
    'Cart',
    'Certificate Manager 2',
    'Certificate Manager 3',
    'Certificate Manager',
    'Change Set',
    'Chat',
    'Chatbot',
    'Checklist Cost',
    'Checklist Fault Tolerant',
    'Checklist Performance',
    'Checklist Security',
    'Checklist',
    'Chime Sdk',
    'Chime',
    'Classic Load Balancer',
    'Clean Rooms',
    'Client Vpn',
    'Client',
    'Cloud Control Api',
    'Cloud Development Kit',
    'Cloud Digital Interface',
    'Cloud Directory',
    'Cloud Extension Ros',
    'Cloud Map',
    'Cloud Wan Segment Network',
    'Cloud Wan Transit Gateway Route Table Attachment',
    'Cloud Wan Virtual Pop',
    'Cloud Wan',
    'Cloud9',
    'Cloudendure Disaster Recovery',
    'Cloudendure Migration',
    'Cloudformation',
    'Cloudfront Functions',
    'Cloudfront',
    'Cloudhsm',
    'Cloudsearch2',
    'Cloudshell',
    'Cloudtrail Cloudtrail Lake',
    'Cloudtrail',
    'Cloudwatch 2',
    'Cloudwatch Cross Account Observability',
    'Cloudwatch Data Protection',
    'Cloudwatch Evidently',
    'Cloudwatch Logs',
    'Cloudwatch Metrics Insights',
    'Cloudwatch Rum',
    'Cloudwatch Synthetics',
    'Cluster',
    'Codeartifact',
    'Codebuild',
    'Codecatalyst',
    'Codecommit',
    'Codedeploy',
    'Codeguru 2',
    'Codeguru',
    'Codepipeline',
    'Codestar',
    'Codewhisperer',
    'Coffee Pot',
    'Cognito',
    'Cold Storage',
    'Command Line Interface',
    'Comprehend Medical',
    'Comprehend',
    'Compute Optimizer',
    'Compute',
    'Config',
    'Connect',
    'Connector',
    'Contact Center',
    'Container 1',
    'Container 2',
    'Container 3',
    'Container Registry Image',
    'Containers',
    'Control Tower',
    'Corporate Data Center',
    'Corretto',
    'Cost And Usage Report',
    'Cost Explorer',
    'Cost Management',
    'Credentials',
    'Custom Billing Manager',
    'Customer Enablement',
    'Customer Engagement',
    'Customer Gateway',
    'D2 Instance',
    'D3 Instance',
    'D3en Instance',
    'Data Encryption Key',
    'Data Exchange For Apis',
    'Data Exchange',
    'Data Lake Resource Icon',
    'Data Pipeline',
    'Data Set',
    'Data Stream',
    'Data Table',
    'Database Migration Service',
    'Database Migration Workflow Job',
    'Database',
    'Datasync Discovery',
    'Datasync',
    'Datazone Business Data Catalog',
    'Datazone Data Portal',
    'Datazone Data Projects',
    'Datazone',
    'Db On Instance2',
    'Deep Learning Amis',
    'Deep Learning Containers',
    'Deepcomposer',
    'Deeplens',
    'Deepracer',
    'Dense Compute Node',
    'Dense Storage Node',
    'Deployment',
    'Deployments',
    'Desired State',
    'Desktop And App Streaming',
    'Detective',
    'Developer Tools',
    'Development Environment',
    'Device Farm',
    'Devops Guru Insights',
    'Devops Guru',
    'Direct Connect',
    'Directory Service',
    'Disk',
    'Distro For Opentelemetry',
    'Document',
    'Documentdb Elastic Clusters',
    'Documentdb With Mongodb Compatibility',
    'Documents',
    'Documents2',
    'Documents3',
    'Door Lock',
    'Download Distribution',
    'Dynamodb Dax',
    'Dynamodb Standard Access Table Class',
    'Dynamodb Standard Infrequent Access Table Class',
    'Dynamodb Stream',
    'Dynamodb',
    'Ec2 Aws Microservice Extractor For Net',
    'Ec2 C6a Instance',
    'Ec2 C6gn Instance',
    'Ec2 C6i Instance',
    'Ec2 C6in Instance',
    'Ec2 C7g Instance',
    'Ec2 C7gn Instance',
    'Ec2 Dl1 Instance',
    'Ec2 G5 Instance',
    'Ec2 G5g Instance',
    'Ec2 Hpc6a Instance',
    'Ec2 Hpc6id Instance',
    'Ec2 I4i Instance',
    'Ec2 Im4gn Instance',
    'Ec2 Image Builder',
    'Ec2 Inf2 Instance',
    'Ec2 Is4gen Instance',
    'Ec2 M1 Mac Instance',
    'Ec2 M6a Instance',
    'Ec2 M6i Instance',
    'Ec2 M6idn Instance',
    'Ec2 M6in Instance',
    'Ec2 P4de Instance',
    'Ec2 R6a Instance',
    'Ec2 R6i Instance',
    'Ec2 R6idn Instance',
    'Ec2 R6in Instance',
    'Ec2 R7iz Instance',
    'Ec2 Trn1 Instance',
    'Ec2 Vt1 Instance',
    'Ec2 X2gd Instance',
    'Ec2 X2idn Instance',
    'Ec2 X2iedn Instance',
    'Ec2 X2iezn Instance',
    'Ec2',
    'Echo',
    'Ecr',
    'Ecs Anywhere',
    'Ecs Copilot Cli',
    'Ecs Service Connect',
    'Ecs Service',
    'Ecs Task',
    'Ecs',
    'Edge Location',
    'Efs Infrequentaccess',
    'Efs Standard',
    'Eks Anywhere',
    'Eks Cloud',
    'Eks Distro',
    'Eks On Outposts',
    'Eks',
    'Elastic Beanstalk',
    'Elastic Block Store Amazon Data Lifecycle Manager',
    'Elastic Block Store Volume Gp3',
    'Elastic Block Store',
    'Elastic Fabric Adapter',
    'Elastic File System Elastic Throughput',
    'Elastic File System Infrequent Access',
    'Elastic File System Intelligent Tiering',
    'Elastic File System One Zone Infrequent Access',
    'Elastic File System One Zone',
    'Elastic File System Standard',
    'Elastic File System',
    'Elastic Inference 2',
    'Elastic Ip Address',
    'Elastic Load Balancing',
    'Elastic Network Adapter',
    'Elastic Network Interface',
    'Elastic Transcoder',
    'Elasticache For Memcached',
    'Elasticache For Redis',
    'Elasticache',
    'Elasticsearch Service',
    'Elemental Link',
    'Elemental Mediaconnect',
    'Elemental Mediaconvert',
    'Elemental Medialive',
    'Elemental Mediapackage',
    'Elemental Mediastore',
    'Elemental Mediatailor',
    'Elemental',
    'Email 2',
    'Email Notification',
    'Email',
    'Emr Engine Mapr M3',
    'Emr Engine Mapr M5',
    'Emr Engine Mapr M7',
    'Emr Engine',
    'Emr',
    'Encrypted Data',
    'Endpoint',
    'Endpoints',
    'Entity Resolution',
    'Event Event Based',
    'Event Resource',
    'Event Time Based',
    'Event',
    'Eventbridge Custom Event Bus Resource',
    'Eventbridge Default Event Bus Resource',
    'Eventbridge Pipes',
    'Eventbridge Saas Partner Event Bus Resource',
    'Eventbridge Scheduler',
    'Eventbridge Schema Registry',
    'Eventbridge Schema',
    'Eventbridge',
    'Express Workflow',
    'External Sdk',
    'External Toolkit',
    'F1 Instance',
    'Factory',
    'Fargate',
    'Fault Injection Simulator',
    'File Cache Hybrid Nfs Linked Datasets',
    'File Cache On Premises Nfs Linked Datasets',
    'File Cache S3 Linked Datasets',
    'File Cache',
    'File Gateway',
    'File System',
    'Filtering Rule',
    'Finding',
    'Finspace',
    'Firetv Stick',
    'Firetv',
    'Firewall Manager',
    'Fleet Management',
    'Flow Logs',
    'Folder',
    'Folders',
    'Forecast',
    'Forums',
    'Fraud Detector',
    'Freertos',
    'Fsx File Gateway',
    'Fsx For Lustre',
    'Fsx For Netapp Ontap',
    'Fsx For Openzfs',
    'Fsx For Windows File Server',
    'Fsx',
    'G3 Instance',
    'G4ad Instance',
    'G4dn',
    'Gamekit',
    'Gamelift 2',
    'Games',
    'Gamesparks',
    'Gateway Load Balancer',
    'Gateway',
    'Gear',
    'General Access Points',
    'General',
    'Generic Application',
    'Generic Database',
    'Generic Firewall',
    'Generic',
    'Genomics Cli',
    'Git Repository',
    'Glacier Deep Archive',
    'Glacier',
    'Global Accelerator',
    'Global Secondary Index',
    'Globe',
    'Glue Crawlers',
    'Glue Data Catalog',
    'Glue Databrew',
    'Glue Elastic Views',
    'Glue',
    'Greengrass',
    'Ground Station',
    'Group Account',
    'Group Auto Scaling Group',
    'Group Aws Cloud Alt',
    'Group Aws Cloud',
    'Group Aws Step Functions Workflow',
    'Group Corporate Data Center',
    'Group Ec2 Instance Contents',
    'Group Elastic Beanstalk',
    'Group Iot Greengrass Deployment',
    'Group Iot Greengrass',
    'Group On Premise',
    'Group Region',
    'Group Security Group',
    'Group Spot Fleet',
    'Group Vpc2',
    'Guardduty',
    'H1 Instance',
    'Habana Gaudi',
    'Hardware Board',
    'Hdfs Cluster',
    'Healthimaging',
    'Healthlake',
    'Healthscribe',
    'High Memory Instance',
    'Honeycode',
    'Hosted Zone',
    'House',
    'Http Notification',
    'Http Protocol',
    'Http2 Protocol',
    'I2',
    'I3 Instance',
    'I3en',
    'Identity Access Management Iam Roles Anywhere',
    'Identity And Access Management',
    'Illustration Desktop',
    'Illustration Devices',
    'Illustration Notification',
    'Illustration Office Building',
    'Illustration Users',
    'Import Export',
    'Inf1',
    'Inferentia',
    'Infrequent Access Storage Class',
    'Inspector',
    'Instance With Cloudwatch2',
    'Instance2',
    'Instances 2',
    'Instances',
    'Intelligent Tiering',
    'Interactive Video',
    'Internet Alt1',
    'Internet Alt2',
    'Internet Alt22',
    'Internet Gateway',
    'Internet Of Things',
    'Internet',
    'Inventory',
    'Iot 1click',
    'Iot Analytics Channel',
    'Iot Analytics Data Store',
    'Iot Analytics Pipeline',
    'Iot Analytics',
    'Iot Button',
    'Iot Core Device Advisor',
    'Iot Core Device Location',
    'Iot Core',
    'Iot Device Defender',
    'Iot Device Gateway',
    'Iot Device Jobs Resource',
    'Iot Device Management Fleet',
    'Iot Device Management',
    'Iot Device Tester',
    'Iot Edukit',
    'Iot Events',
    'Iot Expresslink',
    'Iot Fleetwise',
    'Iot Greengrass Artifact',
    'Iot Greengrass Component Machine Learning',
    'Iot Greengrass Component Nucleus',
    'Iot Greengrass Component Private',
    'Iot Greengrass Component Public',
    'Iot Greengrass Component',
    'Iot Greengrass Interprocess Communication',
    'Iot Greengrass Protocol',
    'Iot Greengrass Recipe',
    'Iot Greengrass Stream Manager',
    'Iot Lorawan Protocol',
    'Iot Over The Air Update',
    'Iot Roborunner',
    'Iot Sailboat',
    'Iot Sitewise Asset Hierarchy',
    'Iot Sitewise Asset Model',
    'Iot Sitewise Asset Properties',
    'Iot Sitewise Asset',
    'Iot Sitewise Data Streams',
    'Iot Sitewise',
    'Iot Thing Freertos Device',
    'Iot Thing Humidity Sensor',
    'Iot Thing Industrial Pc',
    'Iot Thing Plc',
    'Iot Thing Relay',
    'Iot Thing Stacklight',
    'Iot Thing Temperature Humidity Sensor',
    'Iot Thing Temperature Sensor',
    'Iot Thing Temperature Vibration Sensor',
    'Iot Thing Vibration Sensor',
    'Iot Things Graph',
    'Iot Twinmaker',
    'Iq',
    'Item',
    'Items',
    'Json Script',
    'Kendra',
    'Key Management Service External Key Store',
    'Key Management Service',
    'Keyspaces',
    'Kinesis Data Analytics',
    'Kinesis Data Firehose',
    'Kinesis Data Streams',
    'Kinesis Video Streams',
    'Kinesis',
    'Lake Formation',
    'Lambda Function',
    'Lambda',
    'Layers',
    'License Manager Application Discovery',
    'License Manager License Blending',
    'License Manager',
    'Lightbulb',
    'Lightsail For Research',
    'Lightsail',
    'Local Zones',
    'Location Service Geofence',
    'Location Service Map',
    'Location Service Place',
    'Location Service Routes',
    'Location Service Track',
    'Location Service',
    'Logs',
    'Long Term Security Credential',
    'Lookout For Equipment',
    'Lookout For Metrics',
    'Lookout For Vision',
    'Lumberyard',
    'M4 Instance',
    'M5 Instance',
    'M5a Instance',
    'M5d Instance',
    'M5dn Instance',
    'M5n Instance',
    'M5zn Instance',
    'M6g Instance',
    'M6gd Instance',
    'Mac Instance',
    'Machine Learning',
    'Macie',
    'Magnifying Glass 2',
    'Mainframe Modernization Analyzer',
    'Mainframe Modernization Compiler',
    'Mainframe Modernization Converter',
    'Mainframe Modernization Developer',
    'Mainframe Modernization Runtime',
    'Mainframe Modernization',
    'Maintenance Windows',
    'Managed Apache Cassandra Service',
    'Managed Blockchain',
    'Managed Ms Ad',
    'Managed Service For Apache Flink',
    'Managed Service For Grafana',
    'Managed Service For Prometheus',
    'Managed Services',
    'Managed Streaming For Kafka',
    'Managed Workflows For Apache Airflow',
    'Management And Governance',
    'Management Console',
    'Management Console2',
    'Marketplace',
    'Media Services',
    'Mediaconnect Gateway',
    'Medical Emergency',
    'Memorydb For Redis',
    'Mesh',
    'Message',
    'Metrics',
    'Mfa Token',
    'Migration And Transfer',
    'Migration Evaluator',
    'Migration Hub Refactor Spaces Applications',
    'Migration Hub Refactor Spaces Environments',
    'Migration Hub Refactor Spaces Services',
    'Migration Hub',
    'Mobile Application',
    'Mobile Client',
    'Mobile',
    'Monitoring',
    'Monitron',
    'Mq Broker',
    'Mq',
    'Mqtt Protocol',
    'Msk Amazon Msk Connect',
    'Multimedia',
    'Multiple Volumes Resource',
    'Namespace',
    'Nat Gateway',
    'Neptune',
    'Network Access Control List',
    'Network Firewall Endpoints',
    'Network Firewall',
    'Network Load Balancer',
    'Networking And Content Delivery',
    'Neuron Ml Sdk',
    'Nice Dcv',
    'Nice Enginframe',
    'Nimble Studio',
    'Nitro Enclaves',
    'Non Cached Volume',
    'Notebook',
    'Object',
    'Office Building',
    'Omics',
    'One Zone Ia',
    'Open 3d Engine 2',
    'Opensearch Dashboards',
    'Opensearch Ingestion',
    'Opensearch Observability',
    'Opensearch Service Cluster Administrator Node',
    'Opensearch Service Data Node',
    'Opensearch Service Index',
    'Opensearch Service Traces',
    'Opensearch Service Ultrawarm Node',
    'Opsworks Apps',
    'Opsworks Permissions',
    'Opsworks',
    'Optimized Instance',
    'Organizations Account',
    'Organizations Account2',
    'Organizations Management Account',
    'Organizations Management Account2',
    'Organizations Organizational Unit',
    'Organizations Organizational Unit2',
    'Organizations',
    'Outposts 1u And 2u Servers',
    'Outposts Family',
    'Outposts',
    'P2 Instance',
    'P3 Instance',
    'P3dn Instance',
    'P4 Instance',
    'P4d Instance',
    'Panorama',
    'Parallel Cluster',
    'Parameter Store',
    'Patch Manager',
    'Payment Cryptography',
    'Peering',
    'Permissions',
    'Personal Health Dashboard',
    'Personalize',
    'Pinpoint Journey',
    'Pinpoint',
    'Police Emergency',
    'Policy',
    'Polly',
    'Private 5g',
    'Private Certificate Authority',
    'Professional Services',
    'Programming Language',
    'Proton',
    'Q',
    'Quantum Ledger Database',
    'Quantum Technologies',
    'Question',
    'Queue',
    'Quicksight Paginated Reports',
    'Quicksight',
    'R4 Instance',
    'R5 Instance',
    'R5a Instance',
    'R5ad Instance',
    'R5b Instance',
    'R5d Instance',
    'R5gd Instance',
    'R5n Instance',
    'R6g Instance',
    'Rdn Instance',
    'Rds Blue Green Deployments',
    'Rds Instance Alt',
    'Rds Instance',
    'Rds Mariadb Instance Alt',
    'Rds Mariadb Instance',
    'Rds Multi Az Db Cluster',
    'Rds Multi Az',
    'Rds Mysql Instance Alt',
    'Rds Mysql Instance',
    'Rds On Vmware',
    'Rds Optimized Writes',
    'Rds Oracle Instance Alt',
    'Rds Oracle Instance',
    'Rds Piops',
    'Rds Postgresql Instance Alt',
    'Rds Postgresql Instance',
    'Rds Proxy Alt',
    'Rds Proxy',
    'Rds Sql Server Instance Alt',
    'Rds Sql Server Instance',
    'Rds Trusted Language Extensions For Postgresql',
    'Rds',
    'Recover',
    'Red Hat Openshift',
    'Redshift Auto Copy',
    'Redshift Data Sharing Governance',
    'Redshift Ml',
    'Redshift Query Editor V20 Light',
    'Redshift Ra3',
    'Redshift Streaming Ingestion',
    'Redshift',
    'Registry',
    'Rekognition 2',
    'Rekognition Image',
    'Rekognition Video',
    'Replication Time Control',
    'Replication',
    'Reported State',
    'Repost Private',
    'Repost',
    'Rescue',
    'Reserved Instance Reporting',
    'Resilience Hub',
    'Resource Access Manager',
    'Resource Explorer',
    'Resource',
    'Resources',
    'Robomaker',
    'Robotics',
    'Role',
    'Route 53 Application Recovery Controller',
    'Route 53 Readiness Checks',
    'Route 53 Resolver Dns Firewall',
    'Route 53 Resolver Query Logging',
    'Route 53 Resolver',
    'Route 53 Routing Controls',
    'Route 53',
    'Route Table',
    'Router',
    'Rule 2',
    'Rule 3',
    'Rule',
    'Run Command',
    'S3 Batch Operations',
    'S3 File Gateway',
    'S3 Multi Region Access Points',
    'S3 Object Lambda Access Points',
    'S3 Object Lambda',
    'S3 Object Lock',
    'S3 On Outposts Storage',
    'S3 On Outposts',
    'S3 Select',
    'S3 Storage Lens',
    'S3',
    'Sagemaker Canvas',
    'Sagemaker Geospatial Ml',
    'Sagemaker Ground Truth',
    'Sagemaker Model',
    'Sagemaker Notebook',
    'Sagemaker Shadow Testing',
    'Sagemaker Studio Lab',
    'Sagemaker Train',
    'Sagemaker',
    'Saml Token',
    'Satellite',
    'Savings Plans',
    'Search Documents',
    'Secrets Manager',
    'Security Hub',
    'Security Identity And Compliance',
    'Security Lake',
    'Sensor',
    'Server Migration Service',
    'Serverless Application Repository',
    'Serverless',
    'Servers',
    'Service Catalog',
    'Service Management Connector',
    'Service',
    'Servo',
    'Shadow',
    'Shield Shield Advanced',
    'Shield',
    'Shield2',
    'Signer',
    'Simple Ad',
    'Simple Email Service',
    'Simple Storage Service S3 Glacier Instant Retrieval',
    'Simspace Weaver',
    'Simulation',
    'Simulator',
    'Single Sign On',
    'Site To Site Vpn',
    'Snapshot',
    'Snowball Edge',
    'Snowball',
    'Snowcone',
    'Snowmobile',
    'Sns',
    'Source Code',
    'Spot Instance',
    'Sql Workbench',
    'Sqs',
    'Ssl Padlock',
    'Stack',
    'Stack2',
    'Standard Ia',
    'State Manager',
    'Step Functions',
    'Storage Gateway',
    'Storage',
    'Streaming Distribution',
    'Sts Alternate',
    'Sts',
    'Sumerian',
    'Supply Chain',
    'Support',
    'Systems Manager Application Manager',
    'Systems Manager Change Calendar',
    'Systems Manager Change Manager',
    'Systems Manager Compliance',
    'Systems Manager Distributor',
    'Systems Manager Incident Manager',
    'Systems Manager Opscenter',
    'Systems Manager Session Manager',
    'Systems Manager',
    'T2 Instance',
    'T3 Instance',
    'T3a Instance',
    'T4g Instance',
    'Table',
    'Tape Gateway',
    'Tape Storage',
    'Telco Network Builder',
    'Template',
    'Temporary Security Credential',
    'Tensorflow On Aws',
    'Textract Analyze Lending',
    'Textract',
    'Thermostat',
    'Thinkbox Deadline',
    'Thinkbox Draft',
    'Thinkbox Frost',
    'Thinkbox Krakatoa',
    'Thinkbox Sequoia',
    'Thinkbox Stoke',
    'Thinkbox Xmesh',
    'Timestream',
    'Tools And Sdks',
    'Topic 2',
    'Topic',
    'Torchserve',
    'Traditional Server',
    'Training Certification',
    'Trainium Instance',
    'Transcribe',
    'Transfer Family Aws As2',
    'Transfer Family',
    'Transfer For Ftp Resource',
    'Transfer For Ftps Resource',
    'Transfer For Sftp Resource',
    'Transfer For Sftp',
    'Transit Gateway Attachment',
    'Transit Gateway',
    'Translate',
    'Travel',
    'Trusted Advisor',
    'User',
    'Users',
    'Utility',
    'Vault',
    'Verified Access',
    'Verified Permissions',
    'Virtual Gateway',
    'Virtual Node',
    'Virtual Router',
    'Virtual Service',
    'Virtual Tape Library',
    'Vmware Cloud On Aws',
    'Volume Gateway',
    'Volume',
    'Vpc Access Points',
    'Vpc Carrier Gateway',
    'Vpc Lattice',
    'Vpc Network Access Analyzer',
    'Vpc Privatelink',
    'Vpc Reachability Analyzer',
    'Vpc Traffic Mirroring',
    'Vpc Virtual Private Cloud Vpc',
    'Vpc',
    'Vpn Connection',
    'Vpn Gateway',
    'Waf Bad Bot',
    'Waf Bot Control',
    'Waf Bot',
    'Waf Labels',
    'Waf Managed Rule',
    'Waf Rule',
    'Waf',
    'Wavelength',
    'Well Architect Tool',
    'Wickr',
    'Windfarm',
    'Workdocs',
    'Worklink',
    'Workmail',
    'Workspaces Family Amazon Workspaces Core',
    'Workspaces Family Amazon Workspaces',
    'Workspaces Family',
    'Workspaces Thin Client',
    'Workspaces Workspaces Web',
    'Workspaces',
    'X1 Instance2',
    'X1e Instance',
    'Xray',
    'Z1d Instance'
  ];
  stencilList.forEach(name => registerStencil(r, name, stencils));
};
